### PR TITLE
Optimize it a little. #7

### PR DESCRIPTION
**Pull request by lhmouse**
See #7

### CODE REVIEW

**Comment by CarterLi** [comment]
I still think opinion 2 is optimizable. This is my another attempt. 

https://ideone.com/cLAD3P

I tries to load memory before start of the buffer. It should be safe now.

> // 如果在当前内存页至少有一字节可读，就认为整个页都可读

**Comment by lhmouse** [comment]
The mechanism mentioned in paragraph  1 in #7 is not worth trying. Adding a branch, notwithstanding `__builtin_expect()`, nullifies the benefit brought by replacement of `_mm_set1_epi8()` with `_mm_setzero_si128()`, which is only a few cycles.

Reading in front of a string looks OK to me, provided the string is unaligned and you are not reading across pages. A new problem is that, if there are null characters preceding the string, they must be discarded from the result mask. It is still necessary to handle the few leading characters differently.

**Comment by CarterLi** [comment]
See L58  
> mask &= -1u >> len;

**Comment by lhmouse** [comment]
Still I don't think the second paragraph is worth trying. It complexifies the design a lot while brings little. The overhead of the unaligned access in front of the main group is bounded and usually diluted by the function call.

**Comment by CarterLi** [comment]
I dont think so. We should care for small strings as strings are usually small. So does SSO string.
A function call is not expensive, what inline function useful is the optimizion after inlining. Compiler generates strlen fn call if its length is not known at compile time, not means the string is long enough

**Comment by CarterLi** [comment]
Compiler could generates a plain loop per strlen as it is a builtin fn ( MSVC prefer doing this ), then why strlen exists?

**Comment by lhmouse** [comment]
The out-of-line versions exists to allow the address of `strlen()` to be taken.

**Comment by lhmouse** [comment]
Prior to C99, functions need not be declared before they are called. This is called _implicit function declaration_. The following code is valid C89 and calls the out-of-line version of `strlen()`:

```c
main(void){
    char *str = "hello world!";
    printf("len = %u\n", (unsigned)strlen(str));
    return 0;
}
```

**Comment by CarterLi** [comment]
Really? Did you ever do that in real code?

**Comment by lhmouse** [comment]
No. But that is a new story.

If this PR is OK I am ready to merge it.

**Comment by CarterLi** [comment]
Stubborn man 😆 

OK, merge it please.

**Comment by lhmouse** [comment]
There were a few corner cases that got broken. I fixed them.

**Comment by CarterLi** [comment]
Just saw the implementation of strlen on macOS. They use SSE2 and do just the same as my opinion 2. Wow!

image

MSVC uses loop to align pointer, and doesn't use SSE2.

**Comment by lhmouse** [comment]
As I have said, it looks OK. Feel welcome to contribute.

**Comment by lhmouse** [comment]
The optimization above has now been applied to `rawmemchr()`, `strchr()` and their wide variants. In foreseeable future this should be applied to all string functions, it would nonetheless take quite a little time to analysis and rewrite existent code, so please be patient.

**Comment by CarterLi** [comment]
I still want to ask: Why `rawmemchr()` exists? It has no bounds check so that it's not usable except as strlen.

**Comment by lhmouse** [comment]
Back to MS-DOS days some strings are not terminated by zeroes, [but by dollar signs (`$`)](http://spike.scu.edu.au/~barry/interrupts.html#ah09).

It is also quite efficient to search for a character that was captured by a prior regex, because you know it can be nothing else.

**Pull request merged**
